### ISSUE TITLE
Jenkins cas plugin

### ISSUE THREAD

**Issue by mbehlendorf** [cloudogu/ecosystem#205] opened 2016-09-28 14:27 UTC
It seems like our jenkins doesn't use cas anymore.
I can access jenkins without getting redirected to cas.
from jenkins.log:
>   WARNING: Failed to run script file:/var/lib/jenkins/init.groovy.d/init02setrealm.groovy
Sep 28 14:16:19 ces docker/jenkins[3091]: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Sep 28 14:16:19 ces docker/jenkins[3091]: /var/lib/jenkins/init.groovy.d/init02setrealm.groovy: 3: unable to resolve class org.jenkinsci.plugins.cas.CasSecurityRealm
Sep 28 14:16:19 ces docker/jenkins[3091]:  @ line 3, column 1.
Sep 28 14:16:19 ces docker/jenkins[3091]:    import org.jenkinsci.plugins.cas.CasSecurityRealm;
Sep 28 14:16:19 ces docker/jenkins[3091]:    ^
Sep 28 14:16:19 ces docker/jenkins[3091]: 
Sep 28 14:16:19 ces docker/jenkins[3091]: /var/lib/jenkins/init.groovy.d/init02setrealm.groovy: 4: unable to resolve class org.jenkinsci.plugins.cas.protocols.Saml11Protocol
Sep 28 14:16:19 ces docker/jenkins[3091]:  @ line 4, column 1.
Sep 28 14:16:19 ces docker/jenkins[3091]:    import org.jenkinsci.plugins.cas.protocols.Saml11Protocol;
Sep 28 14:16:19 ces docker/jenkins[3091]:    ^
Sep 28 14:16:19 ces docker/jenkins[3091]: 
Sep 28 14:16:19 ces docker/jenkins[3091]: 2 errors

**Comment by mbehlendorf** [comment] 2016-09-28 14:41
already fixed, we just need to update the dogu

**Comment by sdorra** [comment] 2016-09-29 11:12
The issue is still active

**Comment by sdorra** [comment] 2016-09-29 11:25
should be fixed with dogu version 2.7.4-1

**Closed by sdorra** 2016-09-29 11:25 UTC
Labels: bug, jenkins
