### ISSUE TITLE
Routing error after instance registration

### ISSUE THREAD

**Issue by dhuchthausen** [cloudogu/ecosystem#361] opened 2018-01-16 12:30 UTC
After I started the CES setup via Vagrant and I confirmed the registration of my instance, the setup won't continue. Instead I get this error message:

> Routing Error
> Failed to change route.
> Perhaps the setup has already been finished.

For details see the attached journalctl file

[journalctl.txt](https://github.com/cloudogu/ecosystem/files/1635043/journalctl.txt)

![2018-01-16_13h29_32](https://user-images.githubusercontent.com/16819537/34989055-4c8054a2-fac1-11e7-9d82-9f873c0e699a.png)

**Comment by cwolfes** [comment] 2021-11-11 12:42
this may was an error caused by the rebuild of the user backend. Should be fixed by now. When similar issues occur please open an issue here https://github.com/cloudogu/ces-setup/issues.

**Closed by cwolfes** 2021-11-11 12:42 UTC
Labels: setup
